# Generated by Django 4.2.7 on 2023-11-20 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_capybaras_capybara_location_latitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capybara",
            name="description",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="capybara",
            name="parent",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="capybara",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="capybara",
            name="summary",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
